[package]
name = "pandoc_ast"
version = "0.2.1"
authors = ["Oliver Schneider <rust-pandoc-ast885559849564@oli-obk.de>"]
readme = "README.md"
keywords = ["latex", "markdown", "pandoc", "filter", "ast"]
repository = "https://github.com/oli-obk/rust-pandoc-ast"
license-file = "LICENSE"
description = "deserializes and serializes pandoc ast json"
build = "build.rs"

[dependencies]
serde = "0.6"
serde_json = "0.6"

[build-dependencies]
serde_codegen = "0.6"
syntex = "0.29"
